/**
 * Database Schema - CSCI 4177/5709 Tutorial 5
 * 
 * Database: tutorial5_db
 * Collection: books
 * 
 * Document structure:
 * {
 *   _id: ObjectId,        // Auto-generated by MongoDB
 *   title: String,        // Book title
 *   author: String,       // Author name
 *   genre: String,        // Genre (e.g., Fiction, Science, etc.)
 *   year: Number,         // Publication year
 *   inStock: Boolean      // Availability
 * }
 */

const SAMPLE_DOCUMENTS = [
  { title: "The Great Gatsby", author: "F. Scott Fitzgerald", genre: "Fiction", year: 1925, inStock: true },
  { title: "1984", author: "George Orwell", genre: "Dystopian", year: 1949, inStock: true },
  { title: "To Kill a Mockingbird", author: "Harper Lee", genre: "Fiction", year: 1960, inStock: true },
  { title: "Pride and Prejudice", author: "Jane Austen", genre: "Romance", year: 1813, inStock: false },
  { title: "The Hobbit", author: "J.R.R. Tolkien", genre: "Fantasy", year: 1937, inStock: true },
  { title: "Harry Potter and the Philosopher's Stone", author: "J.K. Rowling", genre: "Fantasy", year: 1997, inStock: true },
  { title: "The Catcher in the Rye", author: "J.D. Salinger", genre: "Fiction", year: 1951, inStock: true },
  { title: "Brave New World", author: "Aldous Huxley", genre: "Dystopian", year: 1932, inStock: false },
  { title: "Lord of the Flies", author: "William Golding", genre: "Fiction", year: 1954, inStock: true },
  { title: "Animal Farm", author: "George Orwell", genre: "Dystopian", year: 1945, inStock: true },
  { title: "The Alchemist", author: "Paulo Coelho", genre: "Fiction", year: 1988, inStock: true },
  { title: "Fahrenheit 451", author: "Ray Bradbury", genre: "Dystopian", year: 1953, inStock: true },
];

const DATABASE_NAME = "tutorial5_db";
const COLLECTION_NAME = "books";

module.exports = {
  SAMPLE_DOCUMENTS,
  DATABASE_NAME,
  COLLECTION_NAME,
};
