# Netlify config - update depending on which tutorial you deploy:
# Tutorial 1: base = "", publish = "tutorial1", no build command
# Tutorial 3: base = "tutorial3", command = "npm run build", publish = "dist"
[build]
  base = "tutorial3"
  command = "npm run build"
  publish = "dist"
